# Basic blog info
name: Galaxy Blog
description: Cybersecurity/Aviation/Data insights from 30,000 feet down to the wire.
author: Captain CSEC
avatar: https://raw.githubusercontent.com/barryclark/jekyll-now/master/images/jekyll-logo.png

# Social links (shown in footer)
footer-links:
  github: csec1
  linkedin: captaincsec
  email: you@example.com

# Blog URL and structure
url: https://csec1.github.io
baseurl: ""
permalink: /:title/

# Optional features (can be enabled later)
disqus:
google_analytics:

# Markdown settings
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Plugins
gems:
  - jekyll-sitemap
  - jekyll-feed
